name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Raise file descriptor limit (Ubuntu/Mac)
        if: runner.os != 'Windows'
        run: ulimit -n 4096

      - name: Build web app
        run: npm run build

      - name: Build Electron app (Ubuntu/Mac)
        if: matrix.os != 'windows-latest'
        run: npm run electron:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run electron:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
