name: Build and Release Electron App

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Raise file descriptor limit (Ubuntu/Mac)
        if: runner.os != 'Windows'
        run: ulimit -n 4096

      - name: Build web app
        run: bun run build

      - name: Build Electron app (Ubuntu/Mac)
        if: matrix.os != 'windows-latest'
        run: bun run electron:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Electron app (Windows)
        if: matrix.os == 'windows-latest'
        run: bun run electron:dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
